# Libraries Used

In [2]:
import pickle
import gzip 
import numpy as np
from sklearn.svm import SVC  
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from keras.layers.convolutional import Conv2D
from keras.layers import Dense
from keras.layers.convolutional import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dropout
import keras
from keras.layers import Dense  
from keras.models import Sequential 
from PIL import Image
import os
from sklearn.metrics import confusion_matrix 

/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


# Data Preprocessing

In [3]:
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()

In [4]:
USPSMat  = []
USPSTar  = []
curPath  = 'USPSdata/USPSdata/Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)

In [5]:
X_train = training_data[0]
Y_train = training_data[1]
X_val = validation_data[0]
Y_val = validation_data[1]
X_test = test_data[0]
Y_test = test_data[1]

# SVM with linear kernel

In [24]:
classifier1 = SVC(kernel='linear') 
classifier1.fit(X_train, Y_train)  
TrainingSVM = classifier1.predict(X_train)
accuracy_score(Y_train,TrainingSVM)

0.97246

In [37]:
confusion_matrix(Y_train,TrainingSVM) #Confusion Matrix for training

array([[4822,    1,   16,    8,   13,   25,   18,    3,   23,    3],
       [   2, 5562,   34,   17,    7,   15,    3,    8,   23,    7],
       [  31,   25, 4614,   39,   64,   22,   53,   44,   66,   10],
       [  13,   32,  100, 4647,    2,  149,   18,   51,   66,   23],
       [   9,   10,   25,    0, 4624,    5,   28,    7,    7,  144],
       [  31,   49,   23,  105,   27, 4139,   68,    4,   46,   14],
       [  29,   14,   20,    0,   31,   61, 4783,    0,   13,    0],
       [  10,   35,   47,   15,   65,   13,    1, 4861,    9,  119],
       [  12,   85,   41,   81,   29,  105,   31,   13, 4401,   44],
       [  23,   16,   21,   69,  149,   22,    1,  110,   31, 4546]])

In [39]:
classifier1.fit(X_val, Y_val)
ValSVM1 = classifier1.predict(X_val)
accuracy_score(Y_val,ValSVM1) #SVM linear kernel validation

0.9352

In [40]:
confusion_matrix(Y_val,ValSVM1) #Confusion Matrix for validation

array([[ 971,    0,    4,    2,    1,    2,    3,    2,    5,    1],
       [   0, 1044,    5,    2,    1,    3,    2,    1,    4,    2],
       [   6,    6,  908,    5,   14,    4,   14,   10,   18,    5],
       [   2,    5,   12,  927,    0,   42,    3,    5,   22,   12],
       [   1,    9,    2,    0,  935,    0,    2,    2,    2,   30],
       [   7,   13,    8,   22,    8,  830,   12,    3,    6,    6],
       [   3,    2,    6,    0,    3,   13,  939,    0,    1,    0],
       [   0,   15,   12,    1,   12,    1,    0, 1026,    1,   22],
       [   4,   27,   11,   15,    4,   23,    4,    7,  903,   11],
       [   5,    6,    6,   14,   24,    5,    0,   29,    3,  869]])

In [41]:
TestSVM1 = classifier1.predict(X_test)
accuracy_score(Y_test,TestSVM1) #SVM linear kernel testing

0.9211

In [42]:
confusion_matrix(Y_test,TestSVM1) #Confusion Matrix for testing

array([[ 963,    0,    2,    0,    1,    6,    4,    2,    2,    0],
       [   0, 1116,    2,    2,    0,    2,    4,    0,    9,    0],
       [  12,    4,  912,   15,   20,    1,   19,   17,   30,    2],
       [   3,    5,   20,  915,    0,   24,    3,   15,   17,    8],
       [   1,    2,    3,    0,  922,    2,   10,    1,    3,   38],
       [   9,   10,    5,   31,   13,  793,   15,    2,   10,    4],
       [  12,    3,    8,    1,    7,   14,  912,    0,    1,    0],
       [   2,   20,   21,    2,   14,    0,    0,  932,    7,   30],
       [   5,    7,   10,   21,   10,   31,   13,    9,  857,   11],
       [  10,   10,    3,   10,   46,    8,    1,   21,   11,  889]])

In [43]:
TestSVM2 = classifier1.predict(USPSMat)
accuracy_score(USPSTar,TestSVM2) #SVM linear kernel USPS dataset

0.3714185709285464

In [44]:
confusion_matrix(USPSTar,TestSVM2) #Confusion Matrix for USPS dataset

array([[ 544,    7,  375,   20,  362,  257,   65,   73,   10,  287],
       [  62,  543,  150,   78,  271,  208,   45,  615,   21,    7],
       [ 138,   40, 1219,   58,   55,  286,   60,   97,   31,   15],
       [  80,    6,  156,  929,   23,  609,   10,  105,   41,   41],
       [  14,  119,   39,   10, 1159,  279,   16,  213,   57,   94],
       [  97,   29,  168,   85,   23, 1465,   47,   58,   16,   12],
       [ 227,   14,  358,   19,  104,  541,  669,   25,   14,   29],
       [  41,  371,  325,  170,   79,  410,   29,  489,   50,   36],
       [  55,   44,  176,  128,  146, 1015,   79,   58,  265,   34],
       [  18,  240,  215,  196,  220,  188,   10,  578,  189,  146]])

# SVM with radial basis function and gamma = 1

In [28]:
classifier1 = SVC(kernel='rbf', gamma = 1) 
classifier1.fit(X_train, Y_train)  
TrainingSVM1 = classifier1.predict(X_train)

In [29]:
accuracy_score(Y_train,TrainingSVM1) #SVM rbf kernel and gamma = 1 training

1.0

In [36]:
confusion_matrix(Y_train,TrainingSVM1) #Confusion Matrix for training

array([[4932,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 5678,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 4968,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 5101,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 4859,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 4506,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 4951,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 5175,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 4842,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 4988]])

In [30]:
classifier1.fit(X_val, Y_val)
ValSVM = classifier1.predict(X_val)
accuracy_score(Y_val,ValSVM) #SVM rbf kernel and gamma = 1 validation

1.0

In [45]:
confusion_matrix(Y_val,ValSVM) #Confusion Matrix for validation

array([[ 991,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1064,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,  990,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1030,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  983,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,  915,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  967,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 1090,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 1009,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,  961]])

In [47]:
TestSVM = classifier1.predict(X_test)
accuracy_score(Y_test,TestSVM) #SVM rbf kernel and gamma = 1 testing

0.9211

In [48]:
confusion_matrix(Y_test,TestSVM) #Confusion Matrix for testing

array([[ 963,    0,    2,    0,    1,    6,    4,    2,    2,    0],
       [   0, 1116,    2,    2,    0,    2,    4,    0,    9,    0],
       [  12,    4,  912,   15,   20,    1,   19,   17,   30,    2],
       [   3,    5,   20,  915,    0,   24,    3,   15,   17,    8],
       [   1,    2,    3,    0,  922,    2,   10,    1,    3,   38],
       [   9,   10,    5,   31,   13,  793,   15,    2,   10,    4],
       [  12,    3,    8,    1,    7,   14,  912,    0,    1,    0],
       [   2,   20,   21,    2,   14,    0,    0,  932,    7,   30],
       [   5,    7,   10,   21,   10,   31,   13,    9,  857,   11],
       [  10,   10,    3,   10,   46,    8,    1,   21,   11,  889]])

In [32]:
TestSVM = classifier1.predict(USPSMat)
accuracy_score(USPSTar,TestSVM) #SVM rbf kernel and gamma = 1 USPS dataset

0.10000500025001251

In [ ]:
confusion_matrix(USPSTar,TestSVM) #Confusion Matrix for USPS dataset

# SVM rbf kernel

In [34]:
classifier1 = SVC(kernel='rbf') 
classifier1.fit(X_train, Y_train)  
TrainingSVM = classifier1.predict(X_train)
accuracy_score(Y_train,TrainingSVM) #SVM rbf kernel training

0.93998

In [35]:
confusion_matrix(Y_train,TrainingSVM) #Confusion Matrix for training

array([[4822,    1,   16,    8,   13,   25,   18,    3,   23,    3],
       [   2, 5562,   34,   17,    7,   15,    3,    8,   23,    7],
       [  31,   25, 4614,   39,   64,   22,   53,   44,   66,   10],
       [  13,   32,  100, 4647,    2,  149,   18,   51,   66,   23],
       [   9,   10,   25,    0, 4624,    5,   28,    7,    7,  144],
       [  31,   49,   23,  105,   27, 4139,   68,    4,   46,   14],
       [  29,   14,   20,    0,   31,   61, 4783,    0,   13,    0],
       [  10,   35,   47,   15,   65,   13,    1, 4861,    9,  119],
       [  12,   85,   41,   81,   29,  105,   31,   13, 4401,   44],
       [  23,   16,   21,   69,  149,   22,    1,  110,   31, 4546]])

In [13]:
classifier1.fit(X_val, Y_val)
ValSVM = classifier1.predict(X_val)
accuracy_score(Y_val,ValSVM) #SVM rbf kernel validation

0.9352

In [ ]:
confusion_matrix(Y_val,ValSVM) #Confusion Matrix for validation

In [14]:
TestSVM = classifier1.predict(X_test)
accuracy_score(Y_test,TestSVM) #SVM rbf kernel testing

0.9211

In [ ]:
confusion_matrix(Y_test,TestSVM) #Confusion Matrix for testing

In [83]:
TestSVMUS = classifier1.predict(USPSMat)
accuracy_score(USPSTar,TestSVM) #SVM rbf kernel USPS dataset

ValueError: Found input variables with inconsistent numbers of samples: [19999, 10000]

In [ ]:
confusion_matrix(USPSTar,TestSVM) #Confusion Matrix for USPS dataset

# Random Forest

In [77]:
classifier2 = RandomForestClassifier(n_estimators = 10)
classifier2.fit(X_train, Y_train)  
TrainingRF = classifier2.predict(X_train)
accuracy_score(Y_train,TrainingRF) #Training accuracy 

0.99922

In [78]:
confusion_matrix(Y_train,TrainingRF) #Confusion Matrix for training

array([[4931,    0,    0,    0,    0,    1,    0,    0,    0,    0],
       [   0, 5677,    1,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 4966,    0,    0,    0,    1,    1,    0,    0],
       [   0,    0,    1, 5093,    0,    2,    1,    0,    3,    1],
       [   0,    0,    1,    0, 4855,    0,    1,    0,    1,    1],
       [   0,    0,    0,    2,    0, 4502,    0,    0,    1,    1],
       [   0,    1,    0,    0,    0,    0, 4950,    0,    0,    0],
       [   0,    1,    0,    0,    2,    0,    0, 5171,    0,    1],
       [   0,    0,    2,    2,    0,    1,    0,    1, 4834,    2],
       [   0,    0,    0,    1,    1,    3,    1,    0,    0, 4982]])

In [79]:
classifier2.fit(X_val, Y_val)  
ValRF = classifier2.predict(X_val)
accuracy_score(Y_val,ValRF) #Validation accuracy

0.9984

In [80]:
confusion_matrix(Y_val,ValRF) #Confusion Matrix for validation

array([[ 991,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1064,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,  990,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1029,    0,    1,    0,    0,    0,    0],
       [   0,    0,    0,    0,  983,    0,    0,    0,    0,    0],
       [   0,    0,    1,    2,    0,  912,    0,    0,    0,    0],
       [   1,    0,    0,    0,    0,    0,  966,    0,    0,    0],
       [   0,    1,    0,    0,    0,    0,    0, 1087,    0,    2],
       [   0,    1,    0,    0,    0,    1,    0,    0, 1007,    0],
       [   2,    0,    0,    0,    3,    0,    0,    0,    1,  955]])

In [81]:
ValRF = classifier2.predict(X_test)
accuracy_score(Y_test,ValRF) #Testing accuracy

0.9089

In [82]:
confusion_matrix(Y_test,ValRF) #Confusion Matrix for testing

array([[ 959,    1,    3,    1,    2,    5,    6,    1,    2,    0],
       [   0, 1115,    3,    2,    1,    3,    3,    2,    6,    0],
       [  13,    7,  953,   15,   10,    2,    9,    9,   11,    3],
       [  11,    8,   24,  885,    3,   35,    5,   13,   23,    3],
       [   2,    2,    9,    5,  905,    3,    8,    6,    7,   35],
       [  14,    4,    7,   55,   13,  760,   18,    5,   11,    5],
       [  25,    4,   11,    5,   12,   21,  878,    0,    2,    0],
       [   1,   14,   32,    5,   11,    4,    0,  931,   10,   20],
       [   5,    5,   21,   33,   13,   31,   18,    7,  829,   12],
       [   9,    7,   10,   16,   51,   17,    2,   12,   11,  874]])

In [86]:
TrainingUSRF = classifier2.predict(USPSMat)
accuracy_score(USPSTar,TrainingUSRF) #Accuracy with USPS dataset

0.2745137256862843

In [87]:
confusion_matrix(USPSTar,TrainingUSRF) #Confusion Matrix for USPS dataset

array([[603,  90, 268,  81, 279, 332, 103,  99,  10, 135],
       [ 45, 549, 140,  94, 117, 113,  58, 843,  15,  26],
       [243, 131, 679, 110,  88, 347, 118, 196,  30,  57],
       [156, 114, 180, 684, 122, 435,  31, 178,  25,  75],
       [ 27, 242, 132,  65, 830, 204,  47, 314,  47,  92],
       [204, 129, 152, 229,  67, 971,  69,  94,  25,  60],
       [441, 115, 307,  86, 119, 333, 417, 118,  24,  40],
       [ 90, 562, 240, 134,  79, 194,  51, 482,  45, 123],
       [146, 203, 265, 221, 139, 611, 105,  69, 144,  97],
       [ 68, 324, 301, 270, 203, 183,  27, 418,  75, 131]])

# Convolutional Neural Network

In [50]:
#INITIAL VARIABLES FOR CNN
num_classes = 10  
#image_vector_size = 28*28  
image_size = 784 
#input_shape = (1, 28, 28)
NNX_train = X_train.reshape(X_train.shape[0], 28, 28, 1).astype('float32')
NNX_val = X_val.reshape(X_val.shape[0], 28, 28, 1).astype('float32')
NNX_test = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')
NNY_train = keras.utils.to_categorical(Y_train, num_classes) 
NNY_val = keras.utils.to_categorical(Y_val, num_classes) 
NNY_test = keras.utils.to_categorical(Y_test, num_classes) 
NNX_train = NNX_train / 255
NNX_val = NNX_val / 255
NNX_test = NNX_test / 255
USPSMatnp = np.asarray(USPSMat)
NNUSX_train = USPSMatnp.reshape(USPSMatnp.shape[0], 28, 28, 1).astype('float32')
num_classes = NNY_test.shape[1]

In [51]:
#MODEL DEFINATION
def baseline_model():
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(28, 28, 1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [53]:
# build the model
model = baseline_model()
# Fit the model
model.fit(NNX_train, NNY_train, validation_data=(NNX_test, NNY_test), epochs=20, batch_size=200, verbose=2)

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
 - 22s - loss: 1.3988 - acc: 0.6003 - val_loss: 0.5411 - val_acc: 0.8558
Epoch 2/20
 - 23s - loss: 0.4686 - acc: 0.8652 - val_loss: 0.3737 - val_acc: 0.8921
Epoch 3/20
 - 22s - loss: 0.3733 - acc: 0.8884 - val_loss: 0.3189 - val_acc: 0.9051
Epoch 4/20
 - 22s - loss: 0.3279 - acc: 0.9030 - val_loss: 0.2812 - val_acc: 0.9160
Epoch 5/20
 - 23s - loss: 0.2931 - acc: 0.9119 - val_loss: 0.2517 - val_acc: 0.9232
Epoch 6/20
 - 25s - loss: 0.2623 - acc: 0.9204 - val_loss: 0.2246 - val_acc: 0.9326
Epoch 7/20
 - 24s - loss: 0.2360 - acc: 0.9288 - val_loss: 0.2011 - val_acc: 0.9389
Epoch 8/20
 - 23s - loss: 0.2104 - acc: 0.9368 - val_loss: 0.1831 - val_acc: 0.9434
Epoch 9/20
 - 23s - loss: 0.1878 - acc: 0.9442 - val_loss: 0.1603 - val_acc: 0.9523
Epoch 10/20
 - 23s - loss: 0.1707 - acc: 0.9493 - val_loss: 0.1516 - val_acc: 0.9566
Epoch 11/20
 - 22s - loss: 0.1550 - acc: 0.9537 - val_loss: 0.1346 - val_acc: 0.9599
Epoch 12/20
 - 24s - los

In [54]:
PredictNN = model.predict(NNX_train)
PredNN = []
for i in range(0,50000):
    PredNN.append(np.argmax(PredictNN[i]))
    
accuracy_score(training_data[1],PredNN) #Training Accuracy


0.97948

In [55]:
confusion_matrix(training_data[1],PredNN) #Confusion Matrix for training

array([[4889,    2,    2,    1,    1,    5,   15,    2,    9,    6],
       [   1, 5637,   14,    6,    5,    0,    0,    6,    5,    4],
       [  11,   35, 4833,   20,   10,    0,    3,   34,   17,    5],
       [   5,   14,   20, 4966,    0,   27,    1,   22,   25,   21],
       [   4,   12,    7,    1, 4763,    0,   17,    5,    6,   44],
       [   5,    7,    3,   25,    3, 4412,   18,    5,   10,   18],
       [  15,    9,    2,    0,    7,    9, 4903,    0,    6,    0],
       [   3,   19,   17,    8,   14,    1,    0, 5064,    4,   45],
       [  10,   45,    7,   40,   15,   21,   21,    6, 4646,   31],
       [   9,    9,    0,   16,   47,    9,    2,   28,    7, 4861]])

In [57]:
PredictNNval = model.predict(NNX_val)
PredNN = []
for i in range(0,10000):
    PredNN.append(np.argmax(PredictNNval[i]))
    
accuracy_score(validation_data[1],PredNN) #Validation Accuracy


0.9784

In [58]:
confusion_matrix(validation_data[1],PredNN) #Confusion Matrix for validation

array([[ 982,    0,    1,    0,    0,    1,    1,    1,    1,    4],
       [   0, 1057,    3,    1,    1,    0,    0,    1,    0,    1],
       [   1,    5,  965,    5,    1,    1,    1,    6,    5,    0],
       [   0,    1,    4, 1008,    0,    6,    0,    1,    7,    3],
       [   0,    6,    1,    0,  964,    0,    1,    1,    0,   10],
       [   2,    0,    2,   10,    1,  878,   13,    1,    2,    6],
       [   1,    0,    0,    0,    1,    3,  959,    0,    3,    0],
       [   0,    6,    2,    4,    2,    0,    0, 1066,    0,   10],
       [   1,    7,    3,    6,    2,    3,    5,    2,  976,    4],
       [   2,    3,    0,    6,    8,    3,    0,    8,    2,  929]])

In [59]:
PredictNNtest = model.predict(NNX_test)
PredNN = []
for i in range(0,10000):
    PredNN.append(np.argmax(PredictNNtest[i]))
    
accuracy_score(test_data[1],PredNNtest) #Testing Accuracy

0.9766

In [60]:
confusion_matrix(test_data[1],PredNNtest) #Confusion Matrix for testing

array([[ 973,    0,    1,    1,    0,    0,    1,    1,    3,    0],
       [   0, 1127,    2,    1,    0,    1,    2,    0,    2,    0],
       [   6,    7, 1001,    4,    1,    0,    1,    8,    4,    0],
       [   0,    1,    2,  993,    0,    2,    0,    4,    3,    5],
       [   0,    0,    5,    0,  961,    0,    3,    1,    2,   10],
       [   2,    1,    0,    8,    1,  868,    6,    1,    3,    2],
       [   6,    2,    0,    1,    4,    6,  937,    0,    2,    0],
       [   0,   11,    7,    3,    1,    0,    0,  994,    1,   11],
       [   5,    2,    1,    6,    4,    3,    2,    4,  942,    5],
       [   7,    7,    0,    8,   11,    1,    0,    5,    0,  970]])

In [61]:
PredictNNUS = model.predict(NNUSX_train)
PredNNUS = []
for i in range(len(USPSMat)):
    PredNNUS.append(np.argmax(PredictNNUS[i]))
    
accuracy_score(USPSTar,PredNNUS) #Accuracy with USPS dataset  

0.43212160608030403

In [62]:
confusion_matrix(USPSTar,PredNNUS) #Confusion Matrix for USPS dataset

array([[ 465,    2,   26,  118,  651,   55,   20,  217,  133,  313],
       [ 131,  427,  267,  125,  550,   52,   36,  213,  168,   31],
       [  45,   19, 1445,  243,   40,   96,   32,   33,   44,    2],
       [  25,    5,   65, 1578,    5,  263,    1,   20,   38,    0],
       [   7,    6,   45,   46, 1188,   25,    6,  342,  295,   40],
       [  94,    2,   90,  311,   32, 1329,   14,   30,   88,   10],
       [ 176,   13,  546,  119,   72,  237,  720,   11,   48,   58],
       [  52,   30,   45,  737,   66,   12,    1,  929,  116,   12],
       [ 139,    2,  117, 1023,   23,  183,    7,  233,  247,   26],
       [   7,    6,   56,  510,  112,   29,    0,  741,  225,  314]])

# Logistic Regression

In [64]:
def predictY(X,W):
    return softmax(np.dot(W,X))

def softmax(z):
    sum = np.sum(np.exp(z)) 
    for i in range(10):
        z[i] = np.exp(z[i])/sum
    return z    
        
def hot_vector(Y):
    return np.eye(10)[Y]

In [65]:
Ylog_train = hot_vector(training_data[1])
Ylog_val = hot_vector(Y_val)

In [66]:
W = np.ones((10,784)) #Initialize the weights
LearningRate = 0.01
LogYpredTrain = []

for i in range(50000):
    Y_predicted = predictY(X_train[i],W)
    label = np.argmax(Y_predicted)
    LogYpredTrain.append(label)
    
    for j in range(10):
        grad = (Y_predicted[j] - Ylog_train[i,j]) * X_train[i]
        W[j] = W[j] - LearningRate * grad    

In [67]:
TR_Y = softmax(np.dot(X_train,W.T)) 
Predicted = np.argmax(TR_Y, axis = 1)
TrAccuracy = (training_data[1] == Predicted).sum()
TrAccuracy = TrAccuracy/len(training_data[1])
print(TrAccuracy)  
confusion_matrix(training_data[1],Predicted) #Confusion Matrix for training

0.90686


array([[4777,    0,    9,   21,    6,   37,   20,   11,   46,    5],
       [   0, 5513,   17,   33,    3,   31,    3,   16,   59,    3],
       [  42,   73, 4261,  168,   69,   30,   63,   97,  144,   21],
       [  10,   29,   70, 4549,    2,  228,    7,   74,   81,   51],
       [   9,   33,   22,   13, 4339,   16,   57,   31,   50,  289],
       [  65,   44,   16,  158,   30, 3974,   31,   22,  130,   36],
       [  41,   18,   23,   13,   17,  174, 4621,    4,   35,    5],
       [  20,   32,   46,   15,   30,   12,    2, 4881,   18,  119],
       [  30,  107,   34,  184,   16,  301,   33,   31, 4031,   75],
       [  37,   32,    9,   56,   88,   75,    1,  253,   40, 4397]])

In [68]:
#For validation         
LearningRate = 0.01
LogYpredval = []

for i in range(10000):
    Y_predicted = predictY(X_val[i],W)
    label = np.argmax(Y_predicted)
    LogYpredval.append(label)
    
    for j in range(10):
        grad = (Y_predicted[j] - Ylog_val[i,j]) * X_val[i]
        W[j] = W[j] - LearningRate * grad 

In [69]:
V_Y = softmax(np.dot(X_val,W.T)) 
Predicted = np.argmax(V_Y, axis = 1)
VAccuracy = (validation_data[1] == Predicted).sum()
VAccuracy = VAccuracy/len(validation_data[1])
print(VAccuracy)  
confusion_matrix(validation_data[1],Predicted) #Confusion Matrix for validation

0.918


array([[ 975,    0,    0,    3,    1,    4,    3,    0,    2,    3],
       [   0, 1047,    3,    4,    1,    3,    0,    1,    4,    1],
       [   6,   22,  865,   28,   17,    7,    9,    9,   19,    8],
       [   9,    4,    9,  933,    1,   47,    2,    1,    8,   16],
       [   3,   11,    0,    1,  918,    0,    4,    2,    2,   42],
       [  17,    5,    4,   36,    7,  802,   12,    2,   16,   14],
       [   5,    5,    4,    0,    6,   19,  925,    0,    3,    0],
       [   7,   14,    9,    9,    8,    0,    0,  981,    1,   61],
       [   3,   37,    7,   42,    6,   43,    3,    4,  833,   31],
       [   9,    6,    1,    9,   10,    4,    1,   16,    4,  901]])

In [71]:
T_Y = softmax(np.dot(X_test,W.T)) 
PredictedT = np.argmax(T_Y, axis = 1)
TAccuracy = (test_data[1] == PredictedT).sum()
TAccuracy = TAccuracy/len(test_data[1])
print(TAccuracy) 
confusion_matrix(test_data[1],PredictedT) #Confusion Matrix for testing

0.9033


array([[ 969,    0,    0,    1,    0,    2,    5,    1,    2,    0],
       [   0, 1118,    2,    2,    1,    1,    4,    1,    5,    1],
       [  10,   25,  860,   47,   15,    4,   14,    9,   37,   11],
       [   3,    1,   15,  920,    2,   41,    2,    9,    6,   11],
       [   1,    3,    2,    1,  892,    0,   12,    1,    7,   63],
       [  10,    4,    2,   37,   11,  777,   10,    5,   26,   10],
       [  16,    3,    3,    2,    9,   31,  890,    2,    2,    0],
       [   3,   16,   19,   11,    8,    2,    0,  902,    4,   63],
       [  10,   24,    2,   60,   12,   59,    8,    6,  769,   24],
       [  12,   10,    1,   11,   22,    6,    0,    9,    2,  936]])

In [74]:
TRUS_Y = softmax(np.dot(USPSMat,W.T))
PredictedU = np.argmax(TRUS_Y, axis = 1)
TrAccuracy = (USPSTar == PredictedU).sum()
TrAccuracy = TrAccuracy/len(USPSMat)
print(TrAccuracy)  
confusion_matrix(USPSTar,PredictedU) #Confusion Matrix for USPS dataset

0.3586179308965448


array([[ 629,    4,  228,   79,  181,  194,   47,   75,  163,  400],
       [ 142,  369,  207,  226,  248,  112,   28,  464,  175,   29],
       [ 199,   37, 1151,  182,   45,  172,   56,   40,   77,   40],
       [  81,    4,  123, 1266,   10,  368,    4,   60,   47,   37],
       [  53,   64,   34,   46,  966,  132,   24,  220,  275,  186],
       [ 143,   17,  164,  206,   37, 1213,   56,   58,   78,   28],
       [ 261,   10,  405,   97,   71,  433,  610,   16,   29,   68],
       [ 169,  204,  137,  588,   71,   97,   14,  361,  280,   79],
       [ 247,   31,  104,  287,  115,  598,   73,   50,  395,  100],
       [  37,  129,   92,  494,  139,   78,   11,  463,  345,  212]])

# Combining the Models

In [102]:
final_predm = []
final_predu = []
for i in range(0,10000):
    final_predm.append([ValRF[i], TestSVM[i], PredNN[i], PredictedT[i]])
    
for i in range(0,19999):
    final_predu.append([TrainingUSRF[i], TestSVMUS[i], PredNNUS[i], PredictedU[i]])

In [103]:
def mode(a):  #Implementation mode function
    freq = max(list(map(a.count, a)))
    return list(set(filter(lambda x: a.count(x) == freq, a)))

In [104]:
G = []
U = []
for i in range(len(final_predm)):
    G.append(max(mode(final_predm[i]))) #Obtaining matrix of all labels after majority voting
    
for i in range(len(final_predu)):
    U.append(max(mode(final_predu[i]))) #Obtaining matrix of all labels after majority voting

In [105]:
accuracy_score(G,Y_test)

0.9438

In [106]:
accuracy_score(U,USPSTar)

0.39821991099554976