## Load MNIST on Python 3.x

In [8]:
import pickle
import gzip
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score

In [2]:
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()

## Load USPS on Python 3.x

In [3]:
from PIL import Image
import os
import numpy as np

In [5]:
USPSMat  = []
USPSTar  = []
curPath  = 'USPSdata/USPSdata/Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)

In [104]:
classifier2 = RandomForestClassifier(n_estimators = 150)
classifier2.fit(training_data[0], training_data[1])  
TrainingRF = classifier2.predict(training_data[0])
accuracy_score(training_data[1],TrainingRF) #Training accuracy 

1.0

In [105]:
confusion_matrix(training_data[1],TrainingRF) #Confusion Matrix for training

array([[4932,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 5678,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 4968,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 5101,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 4859,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 4506,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 4951,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 5175,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 4842,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 4988]])

In [106]:
classifier2.fit(validation_data[0], validation_data[1])  
ValRF = classifier2.predict(validation_data[0])
accuracy_score(validation_data[1],ValRF) #Validation accuracy

1.0

In [107]:
confusion_matrix(validation_data[1],ValRF) #Confusion Matrix for validation

array([[ 991,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1064,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,  990,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1030,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  983,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,  915,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  967,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 1090,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 1009,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,  961]])

In [108]:
ValRF = classifier2.predict(test_data[0])
accuracy_score(test_data[1],ValRF) #Testing accuracy

0.9485

In [109]:
confusion_matrix(test_data[1],ValRF) #Confusion Matrix for testing

array([[ 966,    0,    0,    0,    0,    3,    5,    1,    4,    1],
       [   0, 1118,    3,    4,    1,    1,    3,    1,    4,    0],
       [  11,    0,  960,    8,   12,    3,   10,   15,   12,    1],
       [   3,    0,   14,  937,    1,   24,    0,   11,   16,    4],
       [   1,    0,    2,    0,  938,    1,    8,    1,    5,   26],
       [   5,    4,    1,   19,    7,  837,    9,    2,    6,    2],
       [  15,    3,    1,    1,    6,    9,  920,    0,    3,    0],
       [   2,    5,   23,    2,    3,    0,    0,  967,    5,   21],
       [   4,    1,   11,   12,    6,    8,   12,    4,  904,   12],
       [   5,    7,    5,   12,   23,    6,    2,    3,    8,  938]])

In [110]:
TrainingUSRF = classifier2.predict(USPSMat)
accuracy_score(USPSTar,TrainingUSRF) #Accuracy with USPS dataset

0.3576178808940447

In [111]:
confusion_matrix(USPSTar,TrainingUSRF) #Confusion Matrix for USPS dataset

array([[ 603,   19,  240,   46,  454,  164,   72,  238,    3,  161],
       [  29,  535,   94,   57,   68,   93,   24, 1087,   10,    3],
       [ 119,   64,  979,   68,   74,  259,   33,  386,   10,    7],
       [  44,   14,   76, 1064,   82,  385,    5,  284,    5,   41],
       [  13,  215,   42,   19,  998,  174,   14,  475,   16,   34],
       [ 130,   45,  106,  103,   53, 1359,   27,  167,    5,    5],
       [ 353,   69,  200,   30,  101,  393,  605,  226,    8,   15],
       [  20,  434,  234,  169,   40,  250,   37,  803,    2,   11],
       [  46,   75,  125,  183,  135, 1073,   69,  145,  119,   30],
       [  15,  328,  160,  180,  251,  149,    6,  758,   66,   87]])